import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import { Sedan } from "next/font/google";
import "./globals.css";

const spaceGrotesk = Sedan({ subsets: ["latin"], weight: "400" });
export const metadata: Metadata = {
  title: "Tokusei",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={spaceGrotesk.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
